import PDFDocument from 'pdfkit';
import { Agreement } from '@shared/schema';

export class PdfGeneratorService {
  generateAgreementPdf(agreement: Agreement): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // Header
        doc.fontSize(20).font('Helvetica-Bold').text('RENTAL AGREEMENT', { align: 'center' });
        doc.fontSize(12).font('Helvetica').text(`Agreement Number: ${agreement.agreementNumber}`, { align: 'center' });
        doc.moveDown(2);

        // Agreement details
        doc.fontSize(14).font('Helvetica-Bold').text('RENTAL AGREEMENT DETAILS');
        doc.moveDown(0.5);
        
        doc.fontSize(12).font('Helvetica');
        doc.text(`Property Address: ${agreement.propertyAddress}`);
        doc.text(`Monthly Rent: $${agreement.monthlyRent}`);
        if (agreement.securityDeposit) {
          doc.text(`Security Deposit: $${agreement.securityDeposit}`);
        }
        doc.text(`Lease Duration: ${agreement.leaseDuration}`);
        doc.text(`Lease Start Date: ${agreement.leaseStartDate}`);
        doc.text(`Lease End Date: ${agreement.leaseEndDate}`);
        doc.moveDown(1);

        // Tenant information
        doc.fontSize(14).font('Helvetica-Bold').text('TENANT INFORMATION');
        doc.moveDown(0.5);
        
        doc.fontSize(12).font('Helvetica');
        doc.text(`Full Name: ${agreement.tenantFullName}`);
        doc.text(`Email: ${agreement.tenantEmail}`);
        doc.text(`Phone: ${agreement.tenantPhone}`);
        doc.text(`Date of Birth: ${agreement.tenantDob}`);
        doc.text(`Address: ${agreement.tenantAddress}`);
        doc.moveDown(1);

        // Landlord information
        doc.fontSize(14).font('Helvetica-Bold').text('LANDLORD INFORMATION');
        doc.moveDown(0.5);
        
        doc.fontSize(12).font('Helvetica');
        doc.text(`Full Name: ${agreement.landlordFullName}`);
        doc.text(`Email: ${agreement.landlordEmail}`);
        doc.text(`Phone: ${agreement.landlordPhone}`);
        doc.text(`Address: ${agreement.landlordAddress}`);
        doc.moveDown(2);

        // Terms and conditions
        doc.fontSize(14).font('Helvetica-Bold').text('TERMS AND CONDITIONS');
        doc.moveDown(0.5);
        
        doc.fontSize(11).font('Helvetica');
        const terms = [
          '1. The tenant agrees to pay rent on or before the first day of each month.',
          '2. The security deposit will be returned within 30 days of lease termination, subject to property condition.',
          '3. The tenant is responsible for maintaining the property in good condition.',
          '4. No pets are allowed without prior written consent from the landlord.',
          '5. The tenant must provide 30 days written notice before vacating the property.',
          '6. This agreement is governed by local rental laws and regulations.',
          '7. Both parties have verified their identities through SafeRental platform.',
          '8. Any modifications to this agreement must be in writing and signed by both parties.'
        ];

        terms.forEach(term => {
          doc.text(term, { indent: 20 });
          doc.moveDown(0.3);
        });

        doc.moveDown(2);

        // Signatures
        doc.fontSize(14).font('Helvetica-Bold').text('SIGNATURES');
        doc.moveDown(1);
        
        doc.fontSize(12).font('Helvetica');
        doc.text('Tenant Signature: _________________________', { continued: true });
        doc.text('Date: ___________', { align: 'right' });
        doc.moveDown(0.5);
        doc.text(`Print Name: ${agreement.tenantFullName}`);
        doc.moveDown(1.5);
        
        doc.text('Landlord Signature: _________________________', { continued: true });
        doc.text('Date: ___________', { align: 'right' });
        doc.moveDown(0.5);
        doc.text(`Print Name: ${agreement.landlordFullName}`);
        doc.moveDown(2);

        // Footer
        doc.fontSize(10).font('Helvetica').text('This document was generated by SafeRental platform and is legally binding when signed by both parties.', { align: 'center' });
        doc.text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' });

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }
}

export const pdfGeneratorService = new PdfGeneratorService();
