import PDFDocument from 'pdfkit';
import { Agreement } from '@shared/schema';

export class PdfGeneratorService {
  /**
   * Generates a PDF Buffer for a given Rental Agreement
   */
  async generateAgreementPdf(agreement: Agreement): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        // 1. Initialize Document
        const doc = new PDFDocument({ 
          margin: 50, 
          size: 'A4',
          bufferPages: true 
        });
        const chunks: Buffer[] = [];

        // 2. Stream Handling
        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', (err) => reject(err));

        // --- PDF CONTENT START ---

        // Header
        doc.fontSize(20).font('Helvetica-Bold').text('RENTAL AGREEMENT', { align: 'center' });
        doc.fontSize(10).font('Helvetica').text(`Agreement Number: ${agreement.agreementNumber}`, { align: 'center' });
        doc.moveDown(2);

        // Section: Agreement Details
        this.renderSectionHeader(doc, 'RENTAL AGREEMENT DETAILS');
        doc.fontSize(12).font('Helvetica');
        doc.text(`Property Address: ${agreement.propertyAddress}`);
        doc.text(`Monthly Rent: $${agreement.monthlyRent}`);
        if (agreement.securityDeposit) {
          doc.text(`Security Deposit: $${agreement.securityDeposit}`);
        }
        doc.text(`Lease Duration: ${agreement.leaseDuration}`);
        doc.text(`Lease Start Date: ${this.formatDate(agreement.leaseStartDate)}`);
        doc.text(`Lease End Date: ${this.formatDate(agreement.leaseEndDate)}`);
        doc.moveDown(1.5);

        // Section: Tenant Information
        this.renderSectionHeader(doc, 'TENANT INFORMATION');
        doc.fontSize(12).font('Helvetica');
        doc.text(`Full Name: ${agreement.tenantFullName}`);
        doc.text(`Email: ${agreement.tenantEmail}`);
        doc.text(`Phone: ${agreement.tenantPhone}`);
        doc.text(`Date of Birth: ${this.formatDate(agreement.tenantDob)}`);
        doc.text(`Current Address: ${agreement.tenantAddress}`);
        doc.moveDown(1.5);

        // Section: Landlord Information
        this.renderSectionHeader(doc, 'LANDLORD INFORMATION');
        doc.fontSize(12).font('Helvetica');
        doc.text(`Full Name: ${agreement.landlordFullName}`);
        doc.text(`Email: ${agreement.landlordEmail}`);
        doc.text(`Phone: ${agreement.landlordPhone}`);
        doc.text(`Address: ${agreement.landlordAddress}`);
        doc.moveDown(1.5);

        // Section: Terms and Conditions
        this.renderSectionHeader(doc, 'TERMS AND CONDITIONS');
        doc.fontSize(10).font('Helvetica');
        const terms = [
          '1. The tenant agrees to pay rent on or before the first day of each month.',
          '2. The security deposit will be returned within 30 days of lease termination, subject to property condition.',
          '3. The tenant is responsible for maintaining the property in good condition.',
          '4. No pets are allowed without prior written consent from the landlord.',
          '5. The tenant must provide 30 days written notice before vacating the property.',
          '6. This agreement is governed by local rental laws and regulations.',
          '7. Both parties have verified their identities through SafeRental platform.',
          '8. Any modifications to this agreement must be in writing and signed by both parties.'
        ];

        terms.forEach(term => {
          doc.text(term, { indent: 15 });
          doc.moveDown(0.4);
        });
        doc.moveDown(1.5);

        // Section: Signatures (With Page-Break Logic)
        // If we are near the bottom of the page (e.g., 200 units left), start a new page
        if (doc.y > 600) doc.addPage();

        this.renderSectionHeader(doc, 'SIGNATURES');
        doc.fontSize(12).font('Helvetica');
        doc.moveDown(1);

        // Tenant Signature Row
        doc.text('Tenant Signature: _________________________', { continued: true });
        doc.text('Date: ___________', { align: 'right' });
        doc.moveDown(0.5);
        doc.text(`Print Name: ${agreement.tenantFullName}`);
        doc.moveDown(2);

        // Landlord Signature Row
        doc.text('Landlord Signature: _________________________', { continued: true });
        doc.text('Date: ___________', { align: 'right' });
        doc.moveDown(0.5);
        doc.text(`Print Name: ${agreement.landlordFullName}`);

        // Footer (Fixed at bottom)
        const bottom = doc.page.height - 70;
        doc.fontSize(9)
           .fillColor('grey')
           .text('This document was generated by SafeRental platform and is legally binding when signed.', 50, bottom, { align: 'center' })
           .text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' });

        // --- PDF CONTENT END ---
        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  // Helper to keep formatting consistent
  private renderSectionHeader(doc: PDFKit.PDFDocument, title: string) {
    doc.fontSize(13).font('Helvetica-Bold').fillColor('black').text(title);
    doc.moveDown(0.5);
  }

  // Helper to handle date strings/objects safely
  private formatDate(dateInput: any): string {
    if (!dateInput) return 'N/A';
    const date = new Date(dateInput);
    return isNaN(date.getTime()) ? dateInput : date.toLocaleDateString();
  }
}

export const pdfGeneratorService = new PdfGeneratorService();